spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    com.hexlet: info

sentry:
  dsn: https://9da511697ed274233841586f4bbe4639@o4510262112288768.ingest.de.sentry.io/4510262113927248
  send-default-pii: true
